services:
  # Service untuk Database
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: db_sekolah
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql # Otomatis jalankan schema saat startup
      - postgres_data:/var/lib/postgresql/data

  # Service untuk Adminer (GUI Database)
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  # Service untuk Aplikasi Express
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 12345678
      DB_NAME: db_sekolah
      DB_PORT: 5432
      NODE_ENV: development
    depends_on:
      - db
    volumes:
      - .:/app                # Sinkronkan source code
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data: